name: Build and Deploy Angular to IIS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --prod

      - name: Copy files to IIS server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.IIS_HOST }}
          username: ${{ secrets.IIS_USERNAME }}
          password: ${{ secrets.IIS_PASSWORD }}
          source: "dist/todo-service-app/*"
          target: "D:/Lj/My Works/Angular/todo-service-app/dist/todo-service-app/browser"
